stages:
  split_data:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed_data/y_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
  normalize_data:
    cmd: python src/data/normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  grid_search:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    - params.yaml
    params:
    - grid_search.model
    - grid_search.param_grid
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/model.pkl
  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
